import type { RefObject } from "react";
import type { PdfLoadStatus } from "../../../../types/pdf";
import type { RetrievedPdfMeta } from "../../../../types/pdfRetrieval";
import type { PdfRetrievalStatus } from "../../hooks/usePdfRetrieval";
import type { PdfExportController } from "../../types/export";
import type { PdfSessionController } from "../../types/session";

export interface PdfDocumentStageProps {
  hasPdf: boolean;
  loadStatus: PdfLoadStatus;
  statusText: string;
  statusTone: "neutral" | "error" | "success";
  retrievalInputValue: string;
  retrievalStatus: PdfRetrievalStatus;
  canRetryRetrieval: boolean;
  currentPage: number;
  totalPages: number;
  zoom: number;
  pageWidth: number;
  pageHeight: number;
  pageBaseWidth: number;
  pageBaseHeight: number;
  documentMeta: RetrievedPdfMeta | null;
  sourcePdfBlob: Blob | null;
  sourceFileName: string | null;
  pageStageRef: RefObject<HTMLDivElement>;
  canvasContainerRef: RefObject<HTMLDivElement>;
  canvasRef: RefObject<HTMLCanvasElement>;
  onExportControllerChange?: (controller: PdfExportController) => void;
  onSessionControllerChange?: (controller: PdfSessionController) => void;
  onRetrievalInputChange: (value: string) => void;
  onRetrieveDocument: () => void;
  onResetWorkspace: () => void;
  onRetryRetrieval: () => void;
  onMovePage: (direction: -1 | 1) => void;
  onPageInput: (nextPage: number) => void;
  onZoomOut: () => void;
  onZoomIn: () => void;
  onFitToWidth: () => Promise<void>;
}
